version: '3'
services:
    nodejs:
        build:
          context: ./nodejs
        container_name: nodejs
        hostname: nodejs
        ports:
            - "3000:3000" 
        networks:
            - example-net
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017" 
        networks:
            - example-net 
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        links:
            - fluentd
        ports:
            - "80:80" 
        depends_on:
            - nodejs
            - fluentd
        networks:
            - example-net

    fluentd:
        build: ./fluentd
        container_name: fluentd
        hostname: fluentd
        volumes:
            - ./fluentd/conf:/fluentd/etc
        links:
            - mongo
        ports:
            - "24224:24224"
            - "24224:24224/udp"
        depends_on:
            - mongo
        
networks:
  example-net: