services:
  mongodb: #Use Apache as Backend
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  nginx:
    image: nginx-basic-auth
    ports:
      - "80:80"
    depends_on:
      - mongodb
    environment: 
      - FORWARD_HOST=localhost
      - FORWARD_PORT=80
      - BASIC_USERNAME=cuongtnh
      - BASIC_PASSWORD=123qwe123
